// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEA1gfxG-oKzXRbGJmegVXVY5wVw7CHww',
    appId: '1:357156975365:web:28302c95f5ba8e32c33d6c',
    messagingSenderId: '357156975365',
    projectId: 'aprender-ad568',
    authDomain: 'aprender-ad568.firebaseapp.com',
    databaseURL: 'https://aprender-ad568-default-rtdb.firebaseio.com',
    storageBucket: 'aprender-ad568.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsaJMR5NVTM4vXsEoZfO9lEDAa80oYFgA',
    appId: '1:357156975365:android:4e1b47e0885c0b07c33d6c',
    messagingSenderId: '357156975365',
    projectId: 'aprender-ad568',
    databaseURL: 'https://aprender-ad568-default-rtdb.firebaseio.com',
    storageBucket: 'aprender-ad568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOx1kWtHw-AldVvWrr7ati0GIOpz2_dvo',
    appId: '1:357156975365:ios:e94380fa4e9ab2dfc33d6c',
    messagingSenderId: '357156975365',
    projectId: 'aprender-ad568',
    databaseURL: 'https://aprender-ad568-default-rtdb.firebaseio.com',
    storageBucket: 'aprender-ad568.appspot.com',
    iosBundleId: 'com.example.aprender',
  );
}
